include: package:flutter_lints/flutter.yaml
linter:
  rules:
  - always_declare_return_types
  - always_put_control_body_on_new_line
  - always_put_required_named_parameters_first
  - avoid_dynamic_calls
  - avoid_slow_async_io
  - avoid_types_on_closure_parameters
  - avoid_bool_literals_in_conditional_expressions
  - avoid_catches_without_on_clauses
  - avoid_escaping_inner_quotes
  - avoid_field_initializers_in_const_classes
  - avoid_final_parameters
  - prefer_expression_function_bodies
  - prefer_relative_imports
  - prefer_single_quotes
  - unnecessary_statements
